AWSTemplateFormatVersion:"2010-09-09"
Resources:
 MyEc2_Instance: anyname
  Type: AWS::EC2::Instance
  Properties:
     ImageId: ami-06b21ccaeff8cd686
     InstanceType: t2.micro
      KeyName: newone

